### get employee
GET http://localhost:3000/employees/3

### create employee
POST http://localhost:3000/employees/
Content-Type: application/json

{
  "name": "Mr. Employee",
  "managerId": 2,
  "contactInfo": {"email": "employee@acme.com", "phone": "12314"}
}

### update employee
PATCH http://localhost:3000/employees/3
Content-Type: application/json

{
  "name": "Changed employee",
  "managerId": 1,
  "contactInfo": {"email": "changed-employee@acme.com", "phone": "32153"}
}

###assign manager
PATCH http://localhost:3000/employees/3/assign-manager
Content-Type: application/json

{
  "managerId": 2
}

### payment webhook
POST http://localhost:3000/employees/webhooks/payment
Content-Type: application/json

{
  "id": "12039819023809123",
  "status": "paid",
  "amount": 150
}